<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Users\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

Route::post('users/users', [UsersController::class, 'create']);
Route::get('users/users/{id}', [UsersController::class, 'get']);
